package hafnium.steam;

import java.nio.file.Path;
import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

/**
 * 
 * Loosely maps to a Steam application's application manifest file, with helpers
 * to retrieve further related information.
 * 
 */
public interface SteamApp {

    /**
     * The numeric Steamapp ID, stored as a string.
     * 
     * @return
     */
    public String getId();

    public String getName();

    public Path getManifestPath();

    /**
     * Gets the Steam library path. This should typically be three levels above
     * {@link #getInstallPath()} in the tree.
     * 
     * @return
     */
    public Path getLibraryPath();

    /**
     * 
     * @return
     */
    public Path getInstallPath();

    /**
     * An ID generated by Steam identifying a unique build version.
     * 
     * @return
     */
    public String getBuildId();

    /**
     * Get the game's workshop metadata.
     * 
     * @return
     */
    public Optional<? extends SteamAppWorkshop> getWorkshop();

    /**
     * Helper function that returns the workshop items for this application.
     * 
     * 
     * For games without a workshop, an empty list is returned, but an
     * empty list could also indicate a game with a workshop where the user
     * is not subscribed to any workshop items. Check for the presence of
     * the optional returned by {@link #getWorkshop()} to check whether or
     * not the game has any workshop metadata.
     * 
     * @return
     */
    public default List<? extends WorkshopItem> getWorkshopItems() {
        return getWorkshop().map(workshop -> workshop.getItems()).orElse(Collections.emptyList());
    }

    /**
     * Represents a workshop application cache file (ACF). Only games with workshop
     * functionality will have a workshop instance.
     */
    public interface SteamAppWorkshop {

        SteamApp getApp();

        Optional<Instant> getTimeLastUpdated();

        Optional<Instant> getTimeLastAppRan();

        List<? extends WorkshopItem> getItems();

    }

}